CLEVRER_PATH = "data/clevrer"
PIVQA_DATASET_DIR = "data/pivqa"

TIME_SCALES = [1, 2, 3, 4, 5] * 25
QUESTIONS_PER_A_TIME_SCALE = 5

SEED = 42
FRAME_RATE = 25
ERROR_LIMIT = 100
NUM_QUESTIONS_PER_A_SCENE = 50

FLOAT_PRECISION = 2